version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: swift
    directory: /Vendor/OpenAI
    schedule:
      interval: monthly
